### ISSUE TITLE
A9LH support

### ISSUE THREAD

**Issue by dukesrg** [dukesrg/rxTools#13]
- [x] Framebuffer addresses fix
- [ ] FIRM write protection

**Comment by Hartie95** [comment]
Maybe you also need to update the start.s to let it work with a9lh(haven't checked it)
Here is aureinands start.s: https://github.com/AuroraWright/Luma3DS/blob/master/source/start.s

**Comment by mariogamer2** [comment]
It's probably must be changed: https://github.com/roxas75/rxTools/commit/e939f1ba319ffa267fe61b1c99ddac1736bc3631

**Comment by billy-acuna** [comment]
I was looking into the code of stub.ld and it looks like that it is what is causing the framebuffer issue.
If you change "0x08000000" to "0x23F00000" it changes the red screen to black, unfortunably it will broke rxTools on any entrypoint.

Note: "0x23F00000" is the proper offset on any a9lh homebrew/CFW.

Edit: Also, I got a working A9LH version of rxTools 3.0 beta2 with working tools.

**Comment by dukesrg** [comment]
Cherry-pick solution from [arm9loaderhax](/roxas75/rxTools/tree/arm9loaderhax) to [a9lh](/dukesrg/rxTools/tree/dev-a9lh). Only runs from another a9lh launcher for now, direct run causes a bootloop until forced power off. Ought to also change hardcoded AES CTR extraction with proper extraction from NAND CID. Looses sysver detection, need to fix it somehow.

**Comment by dukesrg** [comment]
Cherry-pick framebuffer address fix from 48f40353465bccf7a9a1689b48a2e610506c505e
Fixed boot instability upto 56ac319e78f7a5ed9bb6f1a4dceeb53b2c4a8216
Have only confirmed issues with decryption in al9h now

**Comment by dukesrg** [comment]
Firm decryption issues on A9LH fixed with 130ac4ea4bce8625c522f88ff7c5a5c4bf876f05.

**Comment by dukesrg** [comment]
FIRM write protection will be added along with patch system refactor as a separate patch
