### ISSUE TITLE
SysNAND write protection settings option for tools

### ISSUE THREAD

**Issue by dukesrg** [dukesrg/rxTools#27]

**Comment by mariogamer2** [comment]
This is not implemented here: https://github.com/dukesrg/rxTools/commit/0f4130d274aaac8a6eb86ac059d7de3064856764 ?

**Comment by dukesrg** [comment]
Sure, thanx! Issued to not forgot to implement, but finally forgot to close when implemented :)

**Comment by mariogamer2** [comment]
:)
