### ISSUE TITLE
Implement *_FIRM decryption from NAND

### ISSUE THREAD

**Issue by mariogamer2** [dukesrg/rxTools#41]
**_Important note: Do not work too hard..._**

**Comment by dukesrg** [comment]
Any separate partition decryption, except TWL is already working. Did you mean boot using NATIVE_FIRM from NAND?

**Comment by mariogamer2** [comment]
Yes

**Comment by dukesrg** [comment]
There is no reliable way to identify the firm version, extracting firmware from NATIVE_FIRM from FIRM* partition won't be supported. However firmware extraction from title is working and will be supported.
