### ISSUE TITLE
Can't build with updated ctrulib [da7ecc2]

### ISSUE THREAD

**Issue by PeggerWed** [dukesrg/rxTools#49]
rxTools needs to be updated to compile under latest ctrulib build
_(I know i can edit the \rxTools-DUKESRG\CakeBrah\source\libkhax\khaxinit.cpp, still other warnings appear then)_

`arm-none-eabi-g++ -MMD -MP -MF /d/rxTools/CakeBrah/build/khaxinit.d -g -Wall -Wextra -O3 -mword-relocations -fomit-frame-pointer -ffast-math -march=armv6k -mtune=mpcore -mfloat-abi=hard -I/d/rxTools/CakeBrah/i
nclude -I/c/devkitPro/libctru/include -I/d/rxTools/CakeBrah/build -DARM11 -D_3DS -DARM_ARCH -DLAUNCHER_PATH='"rxTools/sys/code.bin"' -fno-rtti -fno-exceptions -std=gnu++11 -c /d/rxTools/CakeBrah/source/libkhax
/khaxinit.cpp -o khaxinit.o
d:/rxTools/CakeBrah/source/libkhax/khaxinit.cpp: In function 'Result KHAX::IsNew3DS(bool*, u32)':
d:/rxTools/CakeBrah/source/libkhax/khaxinit.cpp:985:47: error: cannot convert 'u8* {aka unsigned char*}' to 'bool*' for argument '1' to 'Result APT_CheckNew3DS(bool*)'
   if (Result error = APT_CheckNew3DS(&isNew3DS))
                                               ^
make[2]: *** [khaxinit.o] Error 1
make[1]: *** [build] Error 2
make[1]: Leaving directory`/d/rxTools/CakeBrah'
make: **\* [all-target-brahma] Error 2`

**Comment by dukesrg** [comment]
~~Just update CakeBrah submodule!~~

**Comment by dukesrg** [comment]
@PeggerWed please explain why do you need an updated ctrulib or just get DevkitPro with all needed packages old but working.

**Comment by PeggerWed** [comment]
Nevermind, i made a batch script to swap ctrulib between an old version and the newest build.

It's more to get the source up to date to build with latest ctrulib, who knows it's of any use now that it has keyboard support in it :D

**Comment by Madridi7** [comment]
@dukesrg 

updated ctrulib is not _needed_ to compile rxtools, but it's needed for other projects. To fix this, can you please update cakebrah submodule?

**Comment by dukesrg** [comment]
Updated toolchain and fixed related issues with this commit 2bae877287950d81c7a277e7730a3b495d87e448
Originaly in dev-cardboost branch.
