### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Margen67** [dukesrg/rxTools#60]
What is the point of this? Couldn't you just add rxtool's menu to Luma, Decrypt9WIP/GodMode9 or something?

Rewriting an outdated CFW when there's better alternatives available doesn't make sense.

**Comment by mariogamer2** [comment]
Make rxtools great again I think... Don't forget it was one (Hu lol THE) most popular CFW before a9lh... Then we don't know why the team stopped dev.

++ I don't see the point on creating this issues.....

**Comment by Madridi7** [comment]
Stay out of it, leave this kind of behavior out of development. If you don't want to see it, then simply dont follow it

**Comment by mariogamer2** [comment]
@Madridi7  Yep exactly

**Comment by dukesrg** [comment]
@Margen67 
All of them actually a combination of the same patch work, like was valuable part of rxTools, and heavily hardcoded. Maybe good looking and works fine, but not versatile and hard to maintain.
